import { test, expect } from '../fixtures/auth.fixture'

test.describe('Sync Engine — Duplicate Sync Protection', () => {
  test.beforeEach(async ({ loginAsOwner }) => {
    await loginAsOwner()
  })

  test('should not create duplicate customer on repeated sync', async ({ page, context }) => {
    await page.goto('/customers')
    await page.waitForTimeout(2000)
    const beforeCount = await page.locator('[data-testid^="customer-row-"]').count()
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await page.goto('/customers')
    await page.waitForTimeout(2000)
    const afterCount = await page.locator('[data-testid^="customer-row-"]').count()
    expect(afterCount - beforeCount).toBeLessThanOrEqual(1)
  })

  test('should not create duplicate pet on repeated sync', async ({ page, context }) => {
    await page.goto('/pets')
    await page.waitForTimeout(2000)
    const beforeCount = await page.locator('[data-testid^="pet-row-"]').count()
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await page.goto('/pets')
    await page.waitForTimeout(2000)
    const afterCount = await page.locator('[data-testid^="pet-row-"]').count()
    expect(afterCount - beforeCount).toBeLessThanOrEqual(1)
  })

  test('should not create duplicate appointment on repeated sync', async ({ page, context }) => {
    await page.goto('/appointments')
    await page.waitForTimeout(2000)
    const beforeCount = await page.locator('[data-testid^="appointment-row-"]').count()
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await page.goto('/appointments')
    await page.waitForTimeout(2000)
    const afterCount = await page.locator('[data-testid^="appointment-row-"]').count()
    expect(afterCount - beforeCount).toBeLessThanOrEqual(1)
  })

  test('should not create duplicate inventory item on repeated sync', async ({ page, context }) => {
    await page.goto('/inventory')
    await page.waitForTimeout(2000)
    const beforeCount = await page.locator('[data-testid^="inventory-row-"]').count()
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await page.goto('/inventory')
    await page.waitForTimeout(2000)
    const afterCount = await page.locator('[data-testid^="inventory-row-"]').count()
    expect(afterCount - beforeCount).toBeLessThanOrEqual(1)
  })

  test('should only store one record when same operation sent twice', async ({ page, context }) => {
    await page.goto('/customers')
    await page.waitForTimeout(2000)
    const beforeCount = await page.locator('[data-testid^="customer-row-"]').count()
    await context.setOffline(true)
    await page.waitForTimeout(500)
    await context.setOffline(false)
    await page.waitForTimeout(3000)
    await page.goto('/customers')
    await page.waitForTimeout(2000)
    const afterCount = await page.locator('[data-testid^="customer-row-"]').count()
    expect(afterCount).toBeGreaterThanOrEqual(beforeCount)
  })
})