import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  decimal,
  integer,
  boolean,
  jsonb,
} from "drizzle-orm/pg-core";
import {
  clinics,
  devices,
  customers,
  pets,
  appointments,
  queues,
  medicalRecords,
  prescriptions,
  prescriptionItems,
  medicines,
  cages,
  hospitalizations,
  hospitalizationRateHistory,
  hospitalizationMonitoring,
  inventoryItems,
  inventoryBatches,
  inventoryTransactions,
  invoices,
  invoiceItems,
  payments,
  auditLogs,
  syncQueue,
  conflictQueue,
  syncLogs,
} from "../server/schema";

export const localUsers = pgTable("local_users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: varchar("email", { length: 255 }).notNull(),
  full_name: varchar("full_name", { length: 255 }).notNull(),
  role: varchar("role", { length: 50 }).notNull().default("CUSTOMER"),
  clinic_id: uuid("clinic_id").notNull(),
  status: varchar("status", { length: 50 }).notNull().default("ACTIVE"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const localSessions = pgTable("local_sessions", {
  id: uuid("id").defaultRandom().primaryKey(),
  user_id: uuid("user_id").notNull(),
  device_id: uuid("device_id").notNull(),
  token: varchar("token", { length: 512 }).notNull(),
  expires_at: timestamp("expires_at").notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const localSchema = {
  localUsers,
  localSessions,
  clinics,
  devices,
  customers,
  pets,
  appointments,
  queues,
  medicalRecords,
  prescriptions,
  prescriptionItems,
  medicines,
  cages,
  hospitalizations,
  hospitalizationRateHistory,
  hospitalizationMonitoring,
  inventoryItems,
  inventoryBatches,
  inventoryTransactions,
  invoices,
  invoiceItems,
  payments,
  auditLogs,
  syncQueue,
  conflictQueue,
  syncLogs,
} as const;

export {
  clinics,
  devices,
  customers,
  pets,
  appointments,
  queues,
  medicalRecords,
  prescriptions,
  prescriptionItems,
  medicines,
  cages,
  hospitalizations,
  hospitalizationRateHistory,
  hospitalizationMonitoring,
  inventoryItems,
  inventoryBatches,
  inventoryTransactions,
  invoices,
  invoiceItems,
  payments,
  auditLogs,
  syncQueue,
  conflictQueue,
  syncLogs,
}
